// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vendas.Models;

namespace Vendas.Migrations
{
    [DbContext(typeof(VendasContext))]
    [Migration("20190814175024_Segundo")]
    partial class Segundo
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Vendas.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nome");

                    b.HasKey("Id");

                    b.ToTable("Department");
                });

            modelBuilder.Entity("Vendas.Models.Venda", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("data");

                    b.Property<int>("status");

                    b.Property<double>("total");

                    b.Property<int?>("vendedorid");

                    b.HasKey("id");

                    b.HasIndex("vendedorid");

                    b.ToTable("Venda");
                });

            modelBuilder.Entity("Vendas.Models.Vendedor", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("departmentId");

                    b.Property<DateTime>("dtNasc");

                    b.Property<string>("email");

                    b.Property<string>("nome");

                    b.Property<double>("salario");

                    b.HasKey("id");

                    b.HasIndex("departmentId");

                    b.ToTable("Vendedor");
                });

            modelBuilder.Entity("Vendas.Models.Venda", b =>
                {
                    b.HasOne("Vendas.Models.Vendedor", "vendedor")
                        .WithMany("venda")
                        .HasForeignKey("vendedorid");
                });

            modelBuilder.Entity("Vendas.Models.Vendedor", b =>
                {
                    b.HasOne("Vendas.Models.Department", "department")
                        .WithMany("Vendedor")
                        .HasForeignKey("departmentId");
                });
#pragma warning restore 612, 618
        }
    }
}
